### ISSUE TITLE
Add field event_log_path

### ISSUE THREAD

**Issue by rkmbaxed** [Graylog2/graylog-schema#106]
**Please describe what you are requesting**
Need to add to the schema.

**Describe what change you are proposing**
Add field `event_log_path` to the schema. Its needed to get information about the origin file path of the file name of the field `event_log_name`. It could be the full path and file name ot the event log.
e.g. if there are many tomcat instances on the same server you have multiple catalina.out files in different folders but the field `event_log_name` only points to catalina.out.

**Describe the log source**
File path of the event log file.

**Comment by miwent** [comment]
Closed by #112
