### ISSUE TITLE
Create mapping for event_severity_level to event_severity

### ISSUE THREAD

**Issue by davethegut** [Graylog2/graylog-schema#78]
## Issue
Currently, we do not map the `event_severity_level` field to `event_severity` , even though our schema docs says: 

`"This will be added by Illuminate Core if only the event_severity_level is defined. This can be mapped from vendor severity levels that do not use the same severity definitions."`

We currently have to map it via lookups manually.

## How to Resolve
Create the logic in core to fix this problem.

**Comment by miwent** [comment]
Duplicate issue in the Illuminate repo that has been closed
